# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

data:
  ORG_ID: "123"
  BILLING_ACCOUNT: "000-000-000"
  STORAGE_LOCATION: "us-central1"

  # TODO: This block prevents certain parts of the configs from being generated
  # which require dependencies to be deployed first.
  #
  # 1. Follow the steps for each field in the block.
  # 2. Remove this block once nothing needs to be disabled.
  DISABLED:
    # The bootstrap module creates the Terraform state bucket and thus
    # its own state cannot be backed up until the state bucket has been created.
    #
    # 1. Deploy the bootstrap module. The state will be created locally in the same directory.
    # 2. Remove this field and run the engine.
    # 3. In the bootstrap module run `terraform init` to backup the bootstrap state to GCS.
    BOOTSTRAP_GCS_BACKEND: true

    # The Forseti module cannot be deployed until the Forseti network has been created.
    # NOTE: If Forseti is not being set up, this field can be removed immediately.
    #
    # 1. Create the Forseti project and network (handled by the "foundation" recipe).
    # 2. Remove this field and run the engine.
    # 3. Apply the configs to create the Forseti module.
    FORSETI_MODULE: true

templates:
- name: "foundation"
  recipe_path: "../recipes/org/foundation.yaml"
  data:
    DEVOPS:
      PROJECT_ID: "example-devops"
      STATE_BUCKET: "example-state-bucket"
      ORG_ADMIN: "group:example-org-admin@example.com"
      PROJECT_OWNERS:
      - "group:example-devops-owners@example.com"
    AUDIT:
      PROJECT_ID: "example-audit"
      ENABLE_LIEN: true
      DATASET_NAME: "1yr_org_audit_logs"
      BUCKET_NAME: "7yr-org-audit-logs"
      AUDITORS: "group:example-dev-auditors@example.com"
    MONITOR:
      PROJECT_ID: "example-monitor"
      DOMAIN: "example.com"
    ORG_POLICIES: {} # Use default org policies.

# Prod
- name: "folder-prod"
  recipe_path: "../recipes/org/folder.yaml"
  output_ref: "foundation.org_dir"
  data:
    DISPLAY_NAME: "prod"
- name: "folder-prod-team1"
  recipe_path: "../recipes/folder/folder.yaml"
  output_ref: "folder-prod.dir"
  data:
    DISPLAY_NAME: "team1"
- name: "project-example-prod-data"
  recipe_path: "../recipes/folder/project.yaml"
  output_ref: "folder-prod-team1.dir"
  data:
    PROJECT_ID: "example-prod-data"
    PROJECT_OWNERS:
    - "group:example-prod-data-owners@example.com"
- name: "project-example-prod-data-resources"
  recipe_path: "../recipes/project/data.yaml"
  output_ref: "project-example-prod-data.dir"
  data:
    PROJECT_ID: "example-prod-data"
    STORAGE_BUCKETS:
    - NAME: "example-bucket"
      IAM_MEMBERS:
      - ROLE: "roles/storage.objectViewer"
        MEMBER: "group:example-readers@example.com"

# Dev
- name: "folder-dev"
  recipe_path: "../recipes/org/folder.yaml"
  output_ref: "foundation.org_dir"
  data:
    DISPLAY_NAME: "dev"
- name: "folder-dev-team1"
  recipe_path: "../recipes/folder/folder.yaml"
  output_ref: "folder-dev.dir"
  data:
    DISPLAY_NAME: "team1"
- name: "project-example-dev-data"
  recipe_path: "../recipes/folder/project.yaml"
  output_ref: "folder-dev-team1.dir"
  data:
    PROJECT_ID: "example-dev-data"
